ai-bot-pro/achatbot

src/cmd/local-terminal-chat/generate_audio2audio.py, src/common/interface.py, src/common/types.py, src/core/llm/llamacpp.py
feat:
- add generate prompt history with system_prompt
- interface ILlm add    `count_tokens(self, text: str | bytes)` method
=> feat: add generate prompt history with system_prompt

demo/asr_whisper_faster.py, src/cmd/be.py, src/cmd/fe.py, src/cmd/init.py, src/cmd/local-terminal-chat/generate_audio2audio.py, src/common/session.py, test/modules/speech/asr/test_whisper_asr.py
fix:
- session add chat history
- change llm_stop
=> fix: session add chat history

src/cmd/be.py, src/cmd/fe.py, src/cmd/local-terminal-chat/generate_audio2audio.py, src/cmd/remote-queue-chat/generate_audio2audio.py, test/common/connector/test_redis_queue.py
fix:
- fe add TerminalChatClient with session and be add Audio2AudioChatWorker
=> fix: fe add TerminalChatClient with session and be add Audio2AudioChatWorker

demo/multi_send.py, docs/settings.json, scripts/py_format.sh, src/cmd/be.py, src/cmd/fe.py, src/cmd/init.py, src/cmd/local-terminal-chat/generate_audio2audio.py, src/common/audio_stream.py, src/common/interface.py, src/common/types.py, src/core/llm/llamacpp.py, src/modules/speech/player/stream_player.py, test/core/llm/test_llamacpp.py, test/modules/speech/player/test_stream_player.py
feat:
- IPlayer interface add operations such as start, stop, pause, and resume
- fe TerminalChatClient add player start stop when recv  PLAY_FRAMES_DONE
- add autopep8 format python & add vs code setting.json
opt:
- stream player: change play_audio send playing audio chunk to buffer (queue.Queue)
fix:
- BE send PLAY_FRAMES_DONE msg when LLM_GENERATE_DONE and tts synthesize over
=> feat: stream player with buffer (queue.Queue)

demo/asr_whisper_faster.py, demo/asr_whisper_mlx.py, demo/asr_whisper_openai.py, demo/asr_whisper_transformers.py, demo/device_cuda.py, demo/list_microphones.py, demo/llm_llamacpp.py, demo/multi_send.py, demo/tts_chat.py, demo/tts_coqui.py, demo/vad_pyannote.py, demo/wakeword_porcupine.py, demo/websocket/game/server.py, src/cmd/be.py, src/cmd/init.py, src/cmd/remote-queue-chat/generate_audio2audio.py, src/common/config.py, src/common/device_cuda.py, src/common/logger.py, src/common/utils/audio_utils.py, src/core/llm/llamacpp.py, src/modules/speech/asr/whisper_asr.py, src/modules/speech/buffering_strategy/silence_end_chunk.py, src/modules/speech/detector/pyannote.py, src/modules/speech/recorder/record.py, src/modules/speech/tts/chat_tts.py, src/modules/speech/tts/coqui_tts.py, test/modules/speech/detector/test_pyannote.py, test/modules/speech/tts/test_gtts.py
run `sh -x ./scripts/py_format.sh`
fix: 
- use PEP 8 formatting. 
- deps ChatTTS format with PEP 8
=> Fix: format with [PEP 8](https://peps.python.org/pep-0008/)

src/cmd/fe.py, src/cmd/init.py, src/common/audio_stream.py, src/modules/speech/player/stream_player.py
fix: 
- stream player check play audio buffer is empty() until play end
- stream player add  on_play_end call back
=> fix: stream player check play audio buffer is empty() until play end

demo/asr_whisper_faster.py, src/cmd/init.py, src/common/device_cuda.py, src/common/factory.py, src/common/types.py, src/core/llm/llamacpp.py, src/modules/speech/tts/base.py, test/core/llm/test_llamacpp.py, test/integration/test_tts_play.py, test/modules/speech/asr/test_whisper_asr.py
fix:
- when use tts stream, don't to buff
- CUDAInfo add verbose to print
=> fix: tts stream

demo/list_microphones.py, demo/record.py, src/cmd/be.py, src/cmd/fe.py, src/cmd/init.py, src/common/audio_stream.py, src/common/interface.py, src/common/types.py, src/common/utils/task.py, src/modules/speech/asr/base.py, src/modules/speech/asr/whisper_asr.py, src/modules/speech/detector/pyannote.py, src/modules/speech/detector/webrtc_vad.py, src/modules/speech/player/stream_player.py, src/modules/speech/recorder/record.py, src/modules/speech/tts/base.py, src/modules/speech/tts/chat_tts.py, src/modules/speech/tts/coqui_tts.py, test/modules/speech/asr/test_whisper_asr.py, test/modules/speech/detector/test_porcupine.py, test/modules/speech/player/test_stream_player.py, test/modules/speech/tts/test_chat.py, test/modules/speech/tts/test_coqui.py, test/modules/speech/tts/test_edge.py, test/modules/speech/tts/test_gtts.py, test/modules/speech/tts/test_pyttsx3.py
=> fix: asr stream

.gitmodules, demo/asr_sense_voice.py, src/cmd/init.py, src/cmd/local-terminal-chat/generate_audio2audio.py, src/common/types.py, src/modules/speech/asr/__init__.py, src/modules/speech/asr/base.py, src/modules/speech/asr/sense_voice_asr.py, src/modules/speech/asr/whisper_asr.py, test/modules/speech/asr/test_whisper_asr.py
feat: 
- add sense_voice_asr with funasr
=> feat: add sense_voice_asr

demo/asr_whisper_groq.py, src/cmd/local-terminal-chat/generate_audio2audio.py, src/common/types.py, src/modules/speech/asr/__init__.py, src/modules/speech/asr/sense_voice_asr.py, src/modules/speech/asr/whisper_groq_asr.py, test/modules/speech/asr/test_whisper_asr.py
feat: 
- add groq_whisper_asr
```
TQDM_DISABLE=True \
TTS_TAG=tts_edge \
RECORDER_TAG=rms_recorder \
ASR_TAG=whisper_groq_asr \
ASR_LANG=zh \
ASR_MODEL_NAME_OR_PATH=whisper-large-v3 \
python -m src.cmd.local-terminal-chat.generate_audio2audio > ./log/std_out.log
```
=> feat: add groq_whisper_asr

src/cmd/be.py, src/cmd/fe.py, src/cmd/init.py, src/cmd/local-terminal-chat/generate_audio2audio.py, src/common/config.py, src/modules/speech/recorder/vad_record.py
feat: integrate vad
```
TQDM_DISABLE=True \
VAD_DETECTOR_TAG=webrtc_vad \
RECORDER_TAG=vad_recorder \
ASR_TAG=sense_voice_asr \
ASR_LANG=zn \
ASR_MODEL_NAME_OR_PATH=./models/FunAudioLLM/SenseVoiceSmall \
TTS_TAG=tts_edge \
python -m src.cmd.local-terminal-chat.generate_audio2audio > ./log/std_out.log
TQDM_DISABLE=True \
VAD_DETECTOR_TAG=webrtc_vad \
RECORDER_TAG=wakeword_vad_recorder \
ASR_TAG=sense_voice_asr \
ASR_LANG=zn \
ASR_MODEL_NAME_OR_PATH=./models/FunAudioLLM/SenseVoiceSmall \
TTS_TAG=tts_edge \
python -m src.cmd.local-terminal-chat.generate_audio2audio > ./log/std_out.log
TQDM_DISABLE=True \
VAD_DETECTOR_TAG=silero_vad \
RECORDER_TAG=vad_recorder \
ASR_TAG=sense_voice_asr \
ASR_LANG=zn \
ASR_MODEL_NAME_OR_PATH=./models/FunAudioLLM/SenseVoiceSmall \
TTS_TAG=tts_edge \
python -m …
```
=> feat: integrate vad

.gitmodules, src/common/types.py, src/modules/speech/tts/cosy_voice_tts.py, test/modules/speech/tts/test_cosy_voice.py
feat: add tts_cosy_voice
paper:  https://arxiv.org/abs/2407.05407v2
colab:
- cpu: https://github.com/weedge/doraemon-nb/blob/main/cosy_voice_cpu.ipynb
- gpu: https://github.com/weedge/doraemon-nb/blob/main/cosy_voice_gpu.ipynb
=> feat: add tts_cosy_voice

src/cmd/remote-queue-chat/generate_audio2audio.py, src/common/types.py, src/core/llm/llamacpp.py, src/modules/speech/tts/base.py, src/modules/speech/tts/chat_tts.py, src/modules/speech/tts/coqui_tts.py, test/modules/speech/tts/test_edge.py
opt: 
- add end silence chunk for tts (default silent_samples = 0.3 s * sample rate)
=> opt: add end_silence_chunk for tts

src/cmd/be.py, src/cmd/init.py, src/cmd/local-terminal-chat/generate_audio2audio.py, src/common/types.py, src/core/llm/llamacpp.py, src/core/llm/personalai.py, src/modules/functions/search/search_api.py
feat: 
- add llm_llamacpp functionary chat function calling model to chat
```
TQDM_DISABLE=True TOKENIZERS_PARALLELISM=true \
ASR_TAG=sense_voice_asr \
ASR_LANG=zn \
ASR_MODEL_NAME_OR_PATH=./models/FunAudioLLM/SenseVoiceSmall \
RECORDER_TAG=wakeword_rms_recorder \
LLM_MODEL_TYPE=chat-func \
LLM_MODEL_NAME=functionary \
LLM_MODEL_PATH=./models/meetkai/functionary-small-v2.4-GGUF/functionary-small-v2.4.Q4_0.gguf \
LLM_TOKENIZER_PATH=./models/meetkai/functionary-small-v2.4-GGUF \
LLM_CHAT_FORMAT=functionary-v2 \
LLM_TOOL_CHOICE=auto \
TTS_TAG=tts_edge \
python -m src.cmd.local-terminal-chat.generate_audio2audio > ./log/std_out.log
```
=> feat: add llm_llamacpp functionary chat function calling model to chat

src/cmd/bots/__init__.py, src/cmd/bots/daily_asr_rtvi_bot.py, src/common/session.py, src/common/types.py, src/common/utils/time.py, src/modules/functions/function.py, src/modules/speech/asr/sense_voice_asr.py, src/modules/speech/asr/whisper_asr.py, src/processors/audio_input_processor.py, src/processors/daily_input_transport_processor.py, src/processors/daily_output_transport_processor.py, src/processors/speech/asr/asr_processor.py, src/processors/speech/asr/base.py, src/services/daily_client.py, src/transports/daily.py, src/types/frames/data_frames.py, test/integration/processors/test_asr_processor.py, test/integration/processors/test_daily_transcription_processor.py
feat:
- add test_daily_transcription_processor
- add AsrProcessor with IAsr and session for pipeline
- add test_asr_processor 
- add daily_asr_rtvi_bot
fix: 
- asyncio.to_thread execute transcription
=> feat: add test_daily_transcription_processor

src/cmd/http/server/fastapi_daily_bot_serve.py, src/processors/rtvi_processor.py
feat: 
- add create random room to join chat with bot; 
ui: 
- set llm chinese system prompt
=> feat: add create random room to join chat with bot; ui: set llm chinese system prompt

.gitignore, demo/tts_chat.py, docs/dev.md, src/cmd/init.py, src/common/types.py, src/modules/speech/asr/base.py, src/modules/speech/asr/whisper_asr.py, src/modules/speech/asr/whisper_groq_asr.py, src/modules/speech/audio_stream/daily_room_stream.py, src/modules/speech/audio_stream/pyaudio_stream.py, src/modules/speech/detector/pyannote.py, src/modules/speech/player/stream_player.py, src/modules/speech/recorder/base.py, src/modules/speech/tts/chat_tts.py, src/types/speech/asr/base.py, src/types/speech/asr/faster_whisper.py, src/types/speech/asr/whisper.py, src/types/speech/audio_stream/pyaudio.py, src/types/speech/detector/pyannote.py, src/types/speech/tts/chat.py, test/modules/speech/audio_stream/test_stream.py, test/modules/speech/player/test_stream_player.py, test/modules/speech/tts/test_chat.py
feat: 
- upgrade chatTTS to support stream tts
fix:
- mv PyannoteDetectorArgs to types/speech/detector
- mv asr arg to types/speech/asr
- mv pyaudio args to types/speech/audio_stream
=> feat: upgrade chatTTS to support stream tts

src/cmd/bots/rag/data_process/pytube_monkey_fix.py, src/cmd/bots/rag/data_process/youtube_audio_transcribe_to_tidb.py
fix:
- fix get_throttling_function_name, see: https://github.com/pytube/pytube/issues/1954
- fix get_transform_plan, see:  https://github.com/pytube/pytube/issues/2006
=> fix: add pytube_monkey_fix

src/cmd/bots/rag/data_process/youtube_audio_transcribe_to_tidb.py
feat: 
- add transcribe_respone to save
- change video download path
=> feat: add transcribe_respone to save and change video download path

src/cmd/bots/rag/daily_langchain_rag_bot.py, src/processors/rtvi_processor.py, src/processors/speech/asr/base.py, src/processors/speech/asr/deepgram_asr_processor.py, src/processors/speech/tts/deepgram_tts_processor.py
feat: 
- add deepgram asr,tts processor
fix: 
- zh system prompt
=> feat: add deepgram asr,tts processor

README.md, deploy/cerebrium/fastapi-daily-chat-bot/cerebrium.toml, pyproject.toml, src/cmd/http/server/fastapi_daily_bot_serve.py
feat: 
- change educator-client ui for cerebrium/fastapi-daily-chat-bot server api;
- add speech_vad_analyzer
=> feat: change educator-client ui for cerebrium/fastapi-daily-chat-bot server api, add speech_vad_analyzer

.gitmodules, README.md, deploy/cerebrium/fastapi-daily-chat-bot/cerebrium.toml, pyproject.toml, src/cmd/bots/base.py, src/cmd/bots/daily_asr_rtvi_bot.py, src/cmd/bots/daily_rtvi_bot.py, src/cmd/bots/rag/daily_langchain_rag_bot.py, src/processors/llm/openai_llm_processor.py, src/processors/speech/asr/asr_processor.py, src/processors/speech/tts/base.py, src/processors/speech/tts/openai_tts_processor.py, src/processors/speech/tts/tts_processor.py, test/integration/processors/test_asr_processor.py
feat: 
- move get asr,llm,tts processor method into bots/base; 
- change pyproject.toml to upgrade
ui:
- add ui/web-client-ui deploy to cloudflare pages, access https://chat-client-weedge.pages.dev/
=> feat: move get asr,llm,tts processor method into bots/base; change pyproject.toml to upgrade

deploy/cerebrium/fastapi-daily-chat-bot/cerebrium.toml, pyproject.toml, src/cmd/bots/__init__.py, src/cmd/bots/daily_bot.py, src/processors/daily_output_transport_processor.py
feat: 
- add simple daily chat bot,
=> feat: add simple daily chat bot

pyproject.toml, src/cmd/bots/base.py, src/cmd/bots/rtvi/daily_asr_rtvi_bot.py, src/cmd/bots/rtvi/daily_rtvi_general_bot.py, src/common/types.py, src/modules/speech/tts/__init__.py, src/processors/llm/base.py, src/processors/llm/openai_llm_processor.py, src/processors/rtvi_processor.py, src/processors/speech/asr/asr_processor.py, src/processors/speech/asr/base.py, src/processors/speech/tts/base.py, src/processors/speech/tts/tts_processor.py, test/modules/speech/tts/test_edge.py
fix: 
- update config message event logic
=> fix: update config message event logic

src/cmd/bots/rtvi/daily_rtvi_general_bot.py, src/processors/rtvi_processor.py
feat: change config, if use tts , to say
=> feat: change config, if use tts , to say

src/cmd/bots/base.py, src/cmd/bots/rtvi/daily_rtvi_general_bot.py, src/processors/rtvi_processor.py
feat: 
- add pipeline config
- fist joined add introduce
=> feat: add pipeline config and fist joined add introduce

pyproject.toml, src/cmd/bots/rtvi/daily_asr_rtvi_bot.py, src/cmd/bots/rtvi/daily_rtvi_bot.py, src/cmd/bots/rtvi/daily_rtvi_general_bot.py, src/common/logger.py, src/modules/speech/vad_analyzer/__init__.py, src/processors/aggregators/llm_response.py, src/processors/aggregators/openai_llm_context.py, src/processors/ai_processor.py, src/processors/frame_log_processor.py, src/processors/llm/openai_llm_processor.py, src/processors/rtvi/rtvi_asr_llm_tts_processor.py, src/processors/rtvi/rtvi_processor.py, src/processors/rtvi/tts_text_processor.py, src/processors/speech/asr/asr_processor.py, src/processors/speech/asr/base.py, src/processors/speech/asr/deepgram_asr_processor.py, src/processors/user_idle_processor.py, src/services/daily_client.py, src/transports/daily.py, src/types/frames/control_frames.py, src/types/frames/data_frames.py, src/types/speech/language.py, test/integration/processors/test_asr_deepgram_processor.py, test/integration/processors/test_rtvi_processor.py
feat: 
- change asr processors (asr modules,deepgram) and mv rtvi
- add daily on_participant_updated event and change ai processor
- add user idle processor for idle timeout to callback bot to say something
- frame_log_processor log for test and add RTVITTSTextProcessor send tts-text daily message
- add rtvi_processor test
=> change asr processors (asr modules,deepgram)  and add daily on_participant_updated event

README.md, deploy/README.md, deploy/cerebrium/fastapi-daily-chat-bot/cerebrium.toml, deploy/docker/fastapi-daily-chat-bot/Dockerfile, deploy/leptonai/README.md, deploy/leptonai/fastapi-daily-chat-bot/photon.py, pyproject.toml, src/cmd/http/server/fastapi_daily_bot_serve.py
feat:
- add fastapi-daily-chat-bot server deploy on leptonai
fix:
- remove daily img, use defualt img deploy on cerebrium
=> deploy: leptonai

src/core/llm/transformers/manual.py, src/core/llm/transformers/manual_vision_llama.py, src/core/llm/transformers/manual_vision_qwen.py, src/core/llm/transformers/pipeline.py, src/types/llm/transformers.py
feat: 
- add do sample params(top_k&top_p ad temperature); repetition_penalty
=> feat: add do sample params(top_k&top_p ad temperature); repetition_penalty

pyproject.toml, src/core/llm/__init__.py, src/core/llm/transformers/base.py, src/core/llm/transformers/manual_vision_molmo.py, test/core/llm/test_transformers_v_llama.py, test/integration/processors/test_vision_processor.py
feat: 
- add transformers vision molmo,  MolmoE-1B-0924, Molmo-7B-O-0924, Molmo-7B-D-0924 on transformers inference(generate) with streamer(streaming); need use A100 40G to run
notebook:
- https://github.com/weedge/doraemon-nb/blob/main/achatbot_vision_qwen_vl.ipynb
fix:
- image inputs and device check
=> feat: add transformers vision molmo

src/cmd/bots/__init__.py, src/cmd/bots/base.py, src/cmd/bots/vision/daily_detect_vision_bot.py, src/modules/vision/detector/yolo.py, src/processors/vision/annotate_processor.py, src/processors/vision/detect_processor.py, src/processors/vision/vision_processor.py, src/types/vision.py, test/integration/processors/test_vision_detect_processor.py
feat:
- add vision detect_processor and unit test;
- add daily_detect_vision_bot
- add confidence IoU selected_classes to predict for yolo vision detector
fix:
- empty eval str
=> feat: add vision detect_processor and unit test; add daily_detect_vision_bot

src/cmd/bots/__init__.py, src/cmd/bots/run.py, src/cmd/bots/vision/livekit_echo_vision_bot.py, src/processors/audio_camera_output_processor.py, src/processors/livekit_input_transport_processor.py, src/services/livekit_client.py, src/transports/livekit.py
feat: 
- add livekit_echo_vision_bot and run it with config `livekit_echo_vision_bot.json`
```json
{
"chat_bot_name": "LivekitEchoVisionBot",
"room_name": "chat-room",
"room_url": "",
"token": "",
"room_manager": {
"tag": "livekit_room",
"args": {
"bot_name": "LivekitBot",
"is_common_session": false
}
},
"services": {},
"config": {},
"config_list": []
}
```
```shell
python -m src.cmd.bots.main -f config/bots/livekit_echo_vision_bot.json
```
fix:
- livekit _convert_input_video_image and write_frame_to_camera frame, 
- camera_out_is_live false use itertools.cycle(List[ImageRawFrame]), true use asyncio.Queue
=> feat: add livekit_echo_vision_bot, fix: livekit _convert_input_video_image and write_frame_to_camera frame, and camera_out_is_live 

pyproject.toml, src/modules/vision/detector/yolo.py, src/types/vision/detector/yolo.py
feat: 
- yolo model weight load to gpu
=> feat: yolo model weight load to gpu

README.md, demo/llm_google_gemini.py, pyproject.toml, src/cmd/bots/rtvi/daily_rtvi_general_bot.py, src/processors/aggregators/openai_llm_context.py, src/processors/llm/base.py, src/processors/llm/google_llm_processor.py, src/processors/llm/openai_llm_processor.py, test/integration/processors/test_google_llm_processor.py
feat: 
- add google_llm_processor and unit test(generative text and use tools)
```shell
python -m unittest test.integration.processors.test_google_llm_processor.TestProcessor.test_run_text
python -m unittest test.integration.processors.test_google_llm_processor.TestProcessor.test_run_tools
```
- add google-gemini function calling with manual and auto tools
- add demo llm_google_gemini.py
=> feat: add google_llm_processor and unit test(gen text and use tools)

demo/aws/upload.py, demo/cloudflare/rest_api.py, demo/image_together_flux.py, demo/insert_podcast.py, src/processors/llm/google_llm_processor.py
feat: 
- gen podcast cover image with flux; 
- upload audio/image file to aws/cloudflare with s3 protocol; 
- insert podcast meta info into cloudflare d1;
=> feat: gen podcast cover image with flux; upload audio/image file to aws/cloudflare with s3 protocol;  insert podcast meta info into cloudflare d1;

README.md, pyproject.toml, src/cmd/bots/__init__.py, src/cmd/bots/base.py, src/cmd/bots/main.py, src/cmd/bots/rtvi/daily_asr_rtvi_bot.py, src/cmd/bots/rtvi/daily_rtvi_bot.py, src/cmd/bots/run.py, src/cmd/bots/websocket_server_bot.py, src/cmd/http/server/fastapi_daily_bot_serve.py, src/common/types.py, src/processors/network/webocket_server_input_processor.py, src/processors/network/webocket_server_output_processor.py, src/transports/websocket_server.py, src/types/network/websocket.py, ui/websocket/simple-demo/README.md, ui/websocket/simple-demo/frames.proto, ui/websocket/simple-demo/index.html
feat: 
- add websocket server transport(input/output)
- add  WebsocketServerBot to run
- add bot_websocket_join when transport_type is websocket, default use room to join room bot
=> feat: add websocket server transport(input/output) and bot

src/cmd/bots/__init__.py, src/cmd/bots/fastapi_websocket_server_bot.py, src/cmd/bots/run.py, src/cmd/http/server/fastapi_daily_bot_serve.py, src/cmd/websocket/server/fastapi_ws_bot_serve.py, src/processors/network/fastapi_webocket_server_input_processor.py, src/processors/network/fastapi_webocket_server_output_processor.py, src/processors/network/webocket_server_input_processor.py, src/transports/fastapi_websocket_server.py, src/types/network/fastapi_websocket.py, src/types/network/websocket.py, ui/websocket/simple-demo/index.html
feat: 
- add fastapi websocket
- add FastapiWebsocketServerBot and websocket fastapi_ws_bot_serve
=> feat: add fastapi websocket

README.md, deploy/README.md, deploy/modal/.gitignore, deploy/modal/README.md, deploy/modal/src/fastapi_serve.py, deploy/modal/src/fastapi_webrtc_audio_bot_serve.py, deploy/modal/src/fastapi_ws_moshi_voice_bot_serve.py, pyproject.toml, src/cmd/bots/base.py, src/cmd/bots/bot_loader.py, src/cmd/http/server/fastapi_daily_bot_serve.py, src/cmd/websocket/server/fastapi_ws_bot_serve.py, src/common/task_manager/base.py, src/processors/audio_input_processor.py, src/processors/voice/moshi_voice_processor.py
feat:
- add deploy modal webrtc_audio_bot_serve
- add deploy modal fastapi_ws_moshi_voice_bot_serve
- change deploy/modal/README.md and pyproject.toml
more modal CD detail see README: [deploy/modal](https://github.com/ai-bot-pro/achatbot/tree/main/deploy/modal)
fix:
- fastapi error with exc_info to trace and TaskManager get_task_num
=> feat: add deploy modal webrtc_audio_bot and fastapi_ws_moshi_voice_bot_serve

deploy/modal/README.md, deploy/modal/src/fastapi_webrtc_audio_bot_serve.py, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/fastapi_ws_moshi_voice_bot_serve.py, pyproject.toml, src/cmd/bots/base.py
feat: 
- empty bot config to run webrtc_audio_bot 
- deploy modal webrtc_vision_bot serve
modal deploy detail see: https://github.com/ai-bot-pro/achatbot/tree/main/deploy/modal#webrtc_vision_bot
=> feat: empty bot config to run webrtc_audio_bot and deploy modal webrtc_vision_bot serve

assets, deploy/modal/src/fastapi_webrtc_audio_bot_serve.py, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/fastapi_ws_moshi_voice_bot_serve.py, pyproject.toml, src/cmd/bots/image/storytelling/utils/helpers.py, src/common/types.py
feat: 
- add deploy modal storytelling bot in webrtc_audio_bot serve
access url: https://storytelling.pages.dev/
=> feat: add deploy modal storytelling bot in webrtc_audio_bot serve

deploy/modal/src/fastapi_webrtc_audio_bot_serve.py, deploy/modal/src/fastapi_webrtc_glm_voice_bot_serve.py, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/fastapi_ws_moshi_voice_bot_serve.py, pyproject.toml, src/cmd/http/server/fastapi_daily_bot_serve.py, src/common/types.py, src/services/help/agora/channel.py, src/services/help/livekit_room.py
fix: 
- fastapi_daily_bot_serve support daily/livekit room bot, agora channel bot, websocket bot, default use daily room bot
=> fix: fastapi_daily_bot_serve support daily/livekit room bot, agora channel bot, websocket bot, default use daily room bot

demo/vad_fsmn.py, src/common/types.py, src/modules/speech/detector/__init__.py, src/modules/speech/detector/fsmn_vad.py, test/modules/speech/detector/test_fsmn_vad.py
feedforward sequential memory networks (FSMN)
- add fsmn_vad speech detector , use tag: fsmn_vad to init [Voice Activity Detector](https://en.wikipedia.org/wiki/Voice_activity_detection)
- add unit test
```shell
CHECK_FRAMES_MODE=0 python -m unittest test.modules.speech.detector.test_fsmn_vad.TestFSMNVADDetector.test_detect
CHECK_FRAMES_MODE=1 python -m unittest test.modules.speech.detector.test_fsmn_vad.TestFSMNVADDetector.test_detect
CHECK_FRAMES_MODE=2 python -m unittest test.modules.speech.detector.test_fsmn_vad.TestFSMNVADDetector.test_detect
CHECK_FRAMES_MODE=1 python -m unittest test.modules.speech.detector.test_fsmn_vad.TestFSMNVADDetector.test_record_detect
```
- [2015. Feedforward sequential memory neural networks without recurrent feedback](https://arxiv.org/abs/1510.02693)
- …
=> feat: add feedforward sequential memory networks (FSMN) VAD from funasr

README.md, demo/tts_openvoicev2.py, pyproject.toml, src/cmd/grpc/speaker/client.py, src/cmd/grpc/speaker/server/serve.py, src/modules/speech/audio_stream/__init__.py, src/modules/speech/player/stream_player.py, src/modules/speech/tts/__init__.py, src/modules/speech/tts/openvoicev2_tts.py, test/modules/speech/tts/test_f5.py
feat: 
- add grpc support for tts_f5 tts_openvoicev2; 
fix: 
- import grpc idl dir (gen idl file don't to edit)
run grpc tts serve
```shell
python -m src.cmd.grpc.speaker.server.serve
```
run grpc tts client
```shell
TTS_TAG=tts_edge IS_RELOAD=1 python -m src.cmd.grpc.speaker.client
TTS_TAG=tts_g IS_RELOAD=1 python -m src.cmd.grpc.speaker.client
TTS_TAG=tts_coqui IS_RELOAD=1 python -m src.cmd.grpc.speaker.client
TTS_TAG=tts_chat IS_RELOAD=1 python -m src.cmd.grpc.speaker.client
TTS_TAG=tts_cosy_voice IS_RELOAD=1 python -m src.cmd.grpc.speaker.client
TTS_TAG=tts_f5 IS_RELOAD=1 python -m src.cmd.grpc.speaker.client
TTS_TAG=tts_openvoicev2 IS_RELOAD=1 python -m src.cmd.grpc.speaker.client
```
=> feat: add grpc support for tts_f5 tts_openvoicev2; fix: import grpc idl dir (gen idl file don't to edit)

demo/tts_kokoro.py, pyproject.toml, src/common/interface.py, src/modules/speech/tts/__init__.py, src/modules/speech/tts/kokoro_onnx_tts.py, src/modules/speech/tts/kokoro_tts.py, src/types/speech/tts/kokoro.py, test/modules/speech/tts/test_kokoro.py
feat:
- add demo/tts_kokoro.py run_torch_kokoro, export_pytorch_voices_to_json, run_onnx_kokoro
- add tts_onnx_kokoro and tts_kokoro
- add kokoro_onnx_tts and kokoro_torch_tts unit test and pass
```shell
python -m unittest test.modules.speech.tts.test_kokoro.TestKOKORO.test_get_voices
python -m unittest test.modules.speech.tts.test_kokoro.TestKOKORO.test_set_voice
python -m unittest test.modules.speech.tts.test_kokoro.TestKOKORO.test_synthesize
TTS_TAG=tts_onnx_kokoro python -m unittest test.modules.speech.tts.test_kokoro.TestKOKORO.test_get_voices
TTS_TAG=tts_onnx_kokoro python -m unittest test.modules.speech.tts.test_kokoro.TestKOKORO.test_set_voice
TTS_TAG=tts_onnx_kokoro KOKORO_ESPEAK_NG_LIB_PATH=/usr/local/lib/libespeak-ng.1.dylib python -m unittest …
```
=> feat: add kokoro tts with onnx and pytorch

src/cmd/grpc/speaker/client.py, src/cmd/grpc/speaker/server/servicers/tts.py, src/common/grpc/idl/tts.proto, src/common/grpc/idl/tts_pb2.py, src/common/grpc/idl/tts_pb2.pyi, src/common/grpc/idl/tts_pb2_grpc.py, src/modules/speech/player/stream_player.py, src/modules/speech/tts/base.py, src/modules/speech/tts/chat_tts.py, src/modules/speech/tts/coqui_tts.py, src/modules/speech/tts/cosy_voice_tts.py, src/modules/speech/tts/edge_tts.py, src/modules/speech/tts/f5_tts.py, src/modules/speech/tts/g_tts.py, src/modules/speech/tts/kokoro_onnx_tts.py, src/modules/speech/tts/kokoro_tts.py, src/modules/speech/tts/openvoicev2_tts.py, src/modules/speech/tts/pyttsx3_tts.py, test/modules/speech/tts/test_edge.py, test/modules/speech/tts/test_kokoro.py, test/modules/speech/tts/test_pyttsx3.py
feat:
- add GetStreamInfo GetVoices tts grpc stub
- add tts_kokoro grpc client/serv
```shell
TTS_TAG=tts_kokoro IS_RELOAD=1 python -m src.cmd.grpc.speaker.client
TTS_TAG=tts_onnx_kokoro IS_RELOAD=1 KOKORO_ESPEAK_NG_LIB_PATH=/usr/local/lib/libespeak-ng.1.dylib KOKORO_LANGUAGE=cmn python -m src.cmd.grpc.speaker.client
```
=> feat: add GetStreamInfo GetVoices tts grpc stub and tts_kokoro grpc client/serve

.gitmodules, README.md, demo/tts_fishspeech.py, pyproject.toml, scripts/pypi_achatbot.sh, src/cmd/grpc/speaker/client.py, src/common/interface.py, src/common/utils/helper.py, src/modules/speech/player/stream_player.py, src/modules/speech/tts/__init__.py, src/modules/speech/tts/cosy_voice2_tts.py, src/modules/speech/tts/cosy_voice_tts.py, src/modules/speech/tts/fish_speech_tts.py, src/types/speech/tts/fish_speech.py, test/modules/speech/tts/test_fish_speech.py
https://weedge.github.io/post/multimoding/voices/fishspeech/
colab 笔记： https://github.com/weedge/doraemon-nb/blob/main/achatbot_fishspeech_tts.ipynb
PS: 
- fish-speech 对公式的支持还不够好，需要微调，加入朗读公式的音频文本数据进行训练。
- 对于学术论文内容的tts场景需要微调
feat:
- add fish_speech tts demo
- add fish_speech_tts module and unit test
```shell
python -m unittest test.modules.speech.tts.test_fish_speech.TestFishSpeechTTS.test_get_voices
python -m unittest test.modules.speech.tts.test_fish_speech.TestFishSpeechTTS.test_set_voice
python -m unittest test.modules.speech.tts.test_fish_speech.TestFishSpeechTTS.test_synthesize
python -m unittest test.modules.speech.tts.test_fish_speech.TestFishSpeechTTS.test_synthesize_speak
FS_WARM_UP_TEXT="hello weedge" python -m unittest …
```
=> feat: add fish_speech tts

pyproject.toml, src/cmd/grpc/speaker/client.py, src/common/interface.py, src/common/utils/audio_utils.py, src/core/llm/transformers/base.py, src/core/llm/transformers/manual_speech_llasa.py, src/core/llm/transformers/manual_voice_glm.py, src/modules/codec/audio/moshi_mimi.py, src/modules/codec/audio/transformers_mimi.py, src/modules/codec/audio/xcodec2.py, src/modules/speech/player/stream_player.py, src/modules/speech/tts/__init__.py, src/modules/speech/tts/base.py, src/modules/speech/tts/llasa_tts.py, src/types/llm/transformers.py, src/types/speech/tts/fish_speech.py, src/types/speech/tts/llasa.py, test/modules/speech/tts/test_llasa.py
feat:
- add TransformersManualSpeechLlasa LM
- add llasa TTS and unit test
``` shell
python -m unittest test.modules.speech.tts.test_llasa.TestLlasaTTS.test_get_voices
python -m unittest test.modules.speech.tts.test_llasa.TestLlasaTTS.test_set_voice
python -m unittest test.modules.speech.tts.test_llasa.TestLlasaTTS.test_synthesize
python -m unittest test.modules.speech.tts.test_llasa.TestLlasaTTS.test_synthesize_speak
LLASA_REF_AUDIO_PATH=./test/audio_files/asr_example_zh.wav \
LLASA_PROMPT_TEXT="欢迎大家来体验达摩院推出的语音识别模型" \
python -m unittest test.modules.speech.tts.test_llasa.TestLlasaTTS.test_synthesize
LLASA_REF_AUDIO_PATH=./test/audio_files/asr_example_zh.wav \
LLASA_PROMPT_TEXT="欢迎大家来体验达摩院推出的语音识别模型" \
python -m unittest test.modules.speech.tts.test_llasa.TestLlasaTTS.test_synthesize_speak …
```
=> feat: add TransformersManualSpeechLlasa LM + xcodec2 -> llasa TTS

.gitmodules, README.md, pyproject.toml, src/common/interface.py, src/common/random.py, src/core/llm/__init__.py, src/core/llm/transformers/base.py, src/core/llm/transformers/manual_vision_img_janus.py, src/core/llm/transformers/manual_vision_img_janus_flow.py, src/core/llm/transformers/manual_vision_img_janus_pro.py, src/core/llm/transformers/manual_vision_qwen.py, src/modules/speech/tts/f5_tts.py, src/processors/vision/vision_processor.py, src/types/llm/transformers.py, test/core/llm/test_transformers_img_janus.py, test/core/llm/test_transformers_v_janus.py
feat:
- add TransformersManualVisionJanusFlow and TransformersManualGenImageJanusFlow
- add test vision(Multimodal Understanding) and gen image janus flow
```shell
LLM_DEVICE=cuda LLM_TAG=llm_transformers_manual_image_janus_flow \
LLM_MODEL_NAME_OR_PATH=./models/deepseek-ai/JanusFlow-1.3B \
VAE_MODEL_NAME_OR_PATH=./models/stabilityai/sdxl-vae \
python -m unittest test.core.llm.test_transformers_img_janus.TestTransformersImgJanus.test_gen_imgs
LLM_DEVICE=cuda LLM_TAG=llm_transformers_manual_vision_janus_flow \
LLM_MODEL_NAME_OR_PATH=./models/deepseek-ai/JanusFlow-1.3B \
python -m unittest test.core.llm.test_transformers_v_janus.TestTransformersVJanus.test_chat_completion_prompts
```
---
- add TransformersManualVisionJanusPro Multimodal Understanding     
- …
=> feat: add janus vision understand + image gen model

deploy/modal/README.md, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, pyproject.toml
feat:
- deploy webrtc_vision_bot with modal
```shell
IMAGE_NAME=janus IMAGE_CONCURRENT_CN=1 IMAGE_GPU=T4 modal serve -e achatbot src/fastapi_webrtc_vision_bot_serve.py
IMAGE_NAME=janus IMAGE_CONCURRENT_CN=1 IMAGE_GPU=L4 LLM_MODEL_NAME_OR_PATH=deepseek-ai/Janus-Pro-7B modal serve -e achatbot src/fastapi_webrtc_vision_bot_serve.py
```
```shell
curl --location 'https://weedge-achatbot--fastapi-webrtc-vision-janus-bot-srv-app-dev.modal.run/bot_join/chat-room/DailyDescribeVisionBot' \
--header 'Authorization: Bearer xxx' \
--header 'Content-Type: application/json' \
--data '{
"chat_bot_name": "DailyDescribeVisionBot",
"room_name": "chat-bot",
"room_url": "",
"token": "",
"services": {
"pipeline": "achatbot",
"vad": "silero",
"asr": "sense_voice",
"llm": "llm_transformers_manual_vision_janus", …
```
=> feat: add webrtc_vision_bot serve on janus vision llm deploy on the modal

.gitmodules, pyproject.toml, src/core/llm/__init__.py, src/core/llm/transformers/manual_vision_deepseek.py, src/processors/vision/vision_processor.py, test/core/llm/test_transformers_v_deepseek.py
feat: 
- add TransformersManualVisionDeepSeekVL2 and test
```shell
LLM_DEVICE=cuda LLM_MODEL_NAME_OR_PATH=./models/deepseek-ai/deepseek-vl2-tiny \
python -m unittest test.core.llm.test_transformers_v_deepseek.TestTransformersVJanus.test_chat_completion_prompts
LLM_DEVICE=cuda LLM_MODEL_NAME_OR_PATH=./models/deepseek-ai/deepseek-vl2-small \
python -m unittest test.core.llm.test_transformers_v_deepseek.TestTransformersVJanus.test_chat_completion_prompts
LLM_DEVICE=cuda LLM_MODEL_NAME_OR_PATH=./models/deepseek-ai/deepseek-vl2 \
python -m unittest test.core.llm.test_transformers_v_deepseek.TestTransformersVJanus.test_chat_completion_prompts
```
---
- [⭐️DeepSeek-VL2: Mixture-of-Experts Vision-Language Models for Advanced Multimodal Understanding](https://github.com/deepseek-ai/DeepSeek-VL2)
=> feat: add TransformersManualVisionDeepSeekVL2 and test

deploy/modal/README.md, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, pyproject.toml, src/core/llm/transformers/manual_vision_deepseek.py, src/types/llm/transformers.py
feat:
- add deepseekvl2 deploy on modal single GPU L4(24GB)(deepseek-vl2-tiny) L40S(48GB)/A100(40GB)(deepseek-vl2-small) A100-80GB/H100 (80GB)(deepseek-vl2)
```shell
IMAGE_NAME=deepseekvl2 IMAGE_CONCURRENT_CN=1 IMAGE_GPU=L4 modal serve -e achatbot src/fastapi_webrtc_vision_bot_serve.py
IMAGE_NAME=deepseekvl2 IMAGE_CONCURRENT_CN=1 IMAGE_GPU=L40S LLM_MODEL_NAME_OR_PATH=deepseek-ai/deepseek-vl2-small modal serve -e achatbot src/fastapi_webrtc_vision_bot_serve.py
IMAGE_NAME=deepseekvl2 IMAGE_CONCURRENT_CN=1 IMAGE_GPU=A100 LLM_MODEL_NAME_OR_PATH=deepseek-ai/deepseek-vl2-small modal serve -e achatbot src/fastapi_webrtc_vision_bot_serve.py
IMAGE_NAME=deepseekvl2 IMAGE_CONCURRENT_CN=1 IMAGE_GPU=A100-80GB LLM_MODEL_NAME_OR_PATH=deepseek-ai/deepseek-vl2 modal serve -e achatbot …
```
=> feat: add deepseekvl2 deploy on modal 

deploy/modal/README.md, deploy/modal/src/fastapi_webrtc_minicpmo_vision_voice_bot_serve.py, pyproject.toml
feat: 
- add deploy webrtc_minicpmo_vision_voice_bot on the modal
- run webrtc_minicpmo_vision_voice_bot serve with task queue(redis)
```shell
IMAGE_NAME=default IMAGE_CONCURRENT_CN=1 IMAGE_GPU=L4 modal serve -e achatbot src/fastapi_webrtc_minicpmo_vision_voice_bot_serve.py
IMAGE_NAME=default IMAGE_CONCURRENT_CN=1 IMAGE_GPU=T4 USE_GPTQ_CKPT=1 modal serve -e achatbot src/fastapi_webrtc_minicpmo_vision_voice_bot_serve.py
```
- curl api to run chat room bot with webrtc (daily)
```shell
curl --location 'https://weedge-achatbot--fastapi-webrtc-minicpmo-omni-bot-srv-app-dev.modal.run/bot_join/chat-room/DailyMiniCPMoVoiceBot' \
--header 'Content-Type: application/json' \
--data '{
"chat_bot_name": "DailyMiniCPMoVoiceBot",
"room_name": "chat-room",
"room_url": "",
"token": "",
"room_manager": { …
```
=> feat: deploy webrtc_minicpmo_vision_voice_bot on the modal

.gitmodules, deploy/modal/README.md, deploy/modal/src/fastapi_webrtc_minicpmo_vision_voice_bot_serve.py, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, pyproject.toml, src/cmd/grpc/speaker/client.py, src/core/llm/__init__.py, src/core/llm/transformers/base.py, src/core/llm/transformers/manual_speech_llasa.py, src/core/llm/transformers/manual_vision_voice_minicpmo.py, src/modules/codec/__init__.py, src/modules/codec/audio/transformers_dac.py, src/modules/codec/audio/transformers_mimi.py, src/modules/speech/player/stream_player.py, src/modules/speech/tts/__init__.py, src/modules/speech/tts/zonos_tts.py, src/types/llm/transformers.py, src/types/speech/tts/zonos.py, src/types/vision/ocr/transformers_got.py, test/modules/codec/test.py, test/modules/speech/tts/test_zonos.py
feat:
- add dac codec and test
```shell
CODEC_TAG=codec_transformers_dac CODEC_MODEL_DIR=./models/descript/dac_16khz \
python -m unittest test.modules.codec.test.TestCodec.test_encode_decode
CODEC_TAG=codec_transformers_dac CODEC_MODEL_DIR=./models/descript/dac_44khz \
python -m unittest test.modules.codec.test.TestCodec.test_encode_decode
```
codec colab笔记： https://github.com/weedge/doraemon-nb/blob/main/achatbot_codec.ipynb
- add zonos tts and test
```shell
ZONOS_LM_CHECKPOINT_DIR=./models/Zyphra/Zonos-v0.1-transformer \
ZONOS_DAC_MODEL_DIR=./models/descript/dac_44khz \
python -m unittest test.modules.speech.tts.test_zonos.TestZonosTTS.test_get_voices
ZONOS_LM_CHECKPOINT_DIR=./models/Zyphra/Zonos-v0.1-transformer \
ZONOS_DAC_MODEL_DIR=./models/descript/dac_44khz \
python -m unittest …
```
=> feat: add zonos tts

deploy/modal/src/llm/trtllm/decoupled/client_grpc.py, deploy/modal/src/llm/trtllm/decoupled/tritonserver.py, deploy/modal/src/llm/trtllm/tts_spark/client_grpc.py, deploy/modal/src/llm/trtllm/tts_spark/ready_model.py, deploy/modal/src/llm/trtllm/tts_spark/tritonserver.py
feat: 
- add decoupled demo
decoupled tritonserver
```shell
modal serve src/llm/trtllm/decoupled/tritonserver.py 
curl -vv -X GET "https://weedge--decoupled-serve-dev.modal.run/v2/health/ready" -H  "accept: application/json"
modal run src/llm/trtllm/decoupled/tritonserver.py 
```
grpc client
```shell
OP=repeat_int32 GRPC_SERVE_URL=r21.modal.host:40765 python src/llm/trtllm/decoupled/client_grpc.py
OP=square_int32 GRPC_SERVE_URL=r21.modal.host:40765 python src/llm/trtllm/decoupled/client_grpc.py
OP=bls_decoupled_sync GRPC_SERVE_URL=r21.modal.host:40765 python src/llm/trtllm/decoupled/client_grpc.py
OP=bls_decoupled_async GRPC_SERVE_URL=r21.modal.host:40765 python src/llm/trtllm/decoupled/client_grpc.py
```
- https://github.com/SparkAudio/Spark-TTS/pull/126
- add triton runtime decoupled …
=> feat: add triton runtime decoupled spark_tts python backend + decoupled tensorrt_llm backend deploy modal

pyproject.toml, src/cmd/grpc/speaker/client.py, src/core/llm/transformers/manual_speech_llama.py, src/modules/speech/player/stream_player.py, src/modules/speech/tts/__init__.py, src/modules/speech/tts/base.py, src/modules/speech/tts/orpheus_tts.py, src/types/speech/tts/orpheus.py, test/modules/speech/tts/test_orpheus.py
feat: 
- add orpheus tts and unit test
```shell
python -m unittest test.modules.speech.tts.test_orpheus.TestOrpheusTTS.test_get_voices
python -m unittest test.modules.speech.tts.test_orpheus.TestOrpheusTTS.test_set_voice
python -m unittest test.modules.speech.tts.test_orpheus.TestOrpheusTTS.test_synthesize
LM_GEN_MAX_NEW_TOKENS=4096 \
TTS_STREAM_FACTOR=1 TTS_TOKEN_OVERLAP_LEN=0 \
TTS_TEXT="Man, the way social media has, um, completely changed how we interact is just wild, right? Like, we're all connected 24/7 but somehow people feel more alone than ever. And don't even get me started on how it's messing with kids' self-esteem and mental health and whatnot." \
python -m unittest test.modules.speech.tts.test_orpheus.TestOrpheusTTS.test_synthesize
LM_GEN_MAX_NEW_TOKENS=4096 \ …
```
=> feat: add orpheus tts

deploy/modal/src/grpc_tts_serve.py, pyproject.toml, src/cmd/grpc/speaker/client.py, src/common/utils/audio_utils.py, src/modules/speech/tts/__init__.py, src/modules/speech/tts/mega3_tts.py, src/types/speech/tts/mega3.py
feat: 
- add dict_file for mega3 tts 
- Smoothly combine audio segments using crossfade transitions for tts client
=> feat: add dict_file for mega3 tts and Smoothly combine audio segments using crossfade transitions for tts client

.gitmodules, deploy/modal/README.md, deploy/modal/src/fastapi_webrtc_kimi_voice_bot_serve.py, deploy/modal/src/llm/transformers/kimi_audio.py, pyproject.toml, scripts/pypi_achatbot.sh, src/cmd/bots/__init__.py, src/cmd/bots/base.py, src/cmd/bots/voice/livekit_asr_kimi_voice_bot.py, src/cmd/bots/voice/livekit_kimi_voice_bot.py, src/core/llm/__init__.py, src/core/llm/transformers/manual_speech_step.py, src/core/llm/transformers/manual_vision_voice_qwen.py, src/core/llm/transformers/manual_voice_kimi.py, src/modules/speech/asr/__init__.py, src/modules/speech/asr/kimi_asr.py, src/processors/voice/kimi_voice_processor.py, src/types/llm/lmgen.py, src/types/omni/kimi_voice.py, test/modules/speech/asr/test_kimi_asr.py, test/modules/speech/asr/test_qwen2_5omni_asr.py
feat:
- add task cases(tokenize, asr, asr_stream, conversation, conversation_stream, conversation_text_audio) 
```shell
IMAGE_GPU=L4 modal run src/llm/transformers/kimi_audio.py --task tokenize
IMAGE_GPU=L40s modal run src/llm/transformers/kimi_audio.py --task asr
IMAGE_GPU=L40s modal run src/llm/transformers/kimi_audio.py --task asr_stream
IMAGE_GPU=L40s modal run src/llm/transformers/kimi_audio.py --task conversation
IMAGE_GPU=L40s modal run src/llm/transformers/kimi_audio.py --task conversation_stream
IMAGE_GPU=L40s modal run src/llm/transformers/kimi_audio.py --task conversation_text_audio
```
- add kimi asr and unit test
```shell
LLM_MODEL_NAME_OR_PATH=./models/moonshotai/Kimi-Audio-7B-Instruct \
LLM_DEVICE=cuda LLM_TORCH_DTYPE=bfloat16 \
python -m unittest …
```
=> add kimi-audio

.gitmodules, deploy/modal/src/download_datasets.py, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/llm/transformers/vlm/fastvlm.py, pyproject.toml, src/core/llm/__init__.py, src/core/llm/transformers/manual_vision_deepseek.py, src/core/llm/transformers/manual_vision_fastvlm.py, src/core/llm/transformers/manual_vision_img_janus_flow.py, src/core/llm/transformers/manual_vision_img_janus_pro.py, src/processors/vision/vision_processor.py, src/types/llm/transformers.py
fastViT:
fastVLM with fastViTHD(Mobile CLIP):
---
podcast: https://podcast-997.pages.dev/podcast/35a15ce5403b4fa786dece19b28208d2
---
colab: 
- fastvlm: https://github.com/weedge/doraemon-nb/blob/main/fastvlm.ipynb
- achatbot+fastvlm: https://github.com/weedge/doraemon-nb/blob/main/achatbot_fastvlm.ipynb
---
feat:
- add llm_transformers_manual_vision_fastvlm
- add DailyDescribeVisionFastVLMBot
```shell
modal run src/download_models.py::download_ckpts --ckpt-urls "https://ml-site.cdn-apple.com/datasets/fastvlm/llava-fastvithd_0.5b_stage3.zip"
modal run src/download_models.py::download_ckpts --ckpt-urls "https://ml-site.cdn-apple.com/datasets/fastvlm/llava-fastvithd_1.5b_stage3.zip"
modal run src/download_models.py::download_ckpts --ckpt-urls …
```
=> add fastvlm

deploy/modal/src/download_models.py, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/llm/transformers/vlm/gemma3.py, pyproject.toml, src/common/chat_history.py, src/core/llm/__init__.py, src/core/llm/transformers/manual_vision_gemma.py, src/processors/vision/vision_processor.py
feat:
- add gemma3 test with modal
```shell
Gemma 3 Medical:
Text only: 27b
Multimodal: 4b
Gemma 3:
Text only: 1b
Multimodal: 4b, 12b, 27b
Gemma 2:
Text only: 2b-v2, 9b, 27b
Gemma:
Text only: 2b, 7b
IMAGE_GPU=A100-80G modal run src/llm/transformers/vlm/gemma3.py --task dump_model
IMAGE_GPU=L4 modal run src/llm/transformers/vlm/gemma3.py --task predict
IMAGE_GPU=L4 modal run src/llm/transformers/vlm/gemma3.py --task predict_stream
LLM_MODEL=google/gemma-3-4b-it-qat-q4_0-unquantized IMAGE_GPU=L4 modal run src/llm/transformers/vlm/gemma3.py --task predict
LLM_MODEL=google/gemma-3-4b-it-qat-q4_0-unquantized IMAGE_GPU=L4 modal run src/llm/transformers/vlm/gemma3.py --task predict_stream
LLM_MODEL=google/gemma-3-12b-it IMAGE_GPU=L40s modal run src/llm/transformers/vlm/gemma3.py --task predict …
```
=> feat: add gemma3 vlm(4b/12b/27b)

deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/llm/transformers/vlm/mimovl.py, pyproject.toml, src/cmd/bots/vision/daily_describe_vision_bot.py, src/core/llm/__init__.py, src/core/llm/transformers/manual_vision_mimo.py, src/types/llm/sampling.py
MiMo-7B (Base/RL-Zero/SFT/RL)
MiMo-VL-7B (SFT/RL)
---
podcast:
- MiMo-7B: https://podcast-997.pages.dev/podcast/b093fe6be5754eec815af4eb21d873a8
- MiMo-VL-7B: https://podcast-997.pages.dev/podcast/2df52cb23a684d04957a34ea3544dbf5
---
> [!TIP]
> - deepseek技术+qwen模型结构 使用高质量数据集(包括合成数据)，在7B模型上复现和提升(量化可在端侧运行)
---
feat:
- add MiMo(Base/Zero-RL/SFT/RL) Text model and MiMo-VL(SFT/RL) vision model test
```shell
IMAGE_GPU=L4 modal run src/llm/transformers/vlm/mimovl.py --task dump_text_model
IMAGE_GPU=L4 LLM_MODEL=XiaomiMiMo/MiMo-7B-Base modal run src/llm/transformers/vlm/mimovl.py --task predict_text
IMAGE_GPU=L4 LLM_MODEL=XiaomiMiMo/MiMo-7B-RL-Zero modal run src/llm/transformers/vlm/mimovl.py --task predict_text
IMAGE_GPU=L4 LLM_MODEL=XiaomiMiMo/MiMo-7B-SFT modal run …
```
=> feat: add MiMo-VL(SFT/RL)

deploy/modal/src/download_models.py, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/llm/transformers/vlm/keye.py, deploy/modal/src/remove_volume_data.py, deploy/modal/src/video/meigen_multitalk.py, pyproject.toml, src/cmd/be.py, src/cmd/bots/base.py, src/core/llm/__init__.py, src/core/llm/transformers/base.py, src/core/llm/transformers/manual_vision_keye.py, src/core/llm/transformers/manual_vision_mimo.py, src/processors/vision/vision_processor.py, src/types/llm/sampling.py
---
AI Podcast:
- Kwai Keye-VL: https://podcast-997.pages.dev/podcast/ccefdb0a75514b2887c2fb2f9673c110
---
feat:
- add keye vlm
- add transformers manual_vision_keye module
- add llm_transformers_manual_vision_keye
- add lm_gen_thinking mode: auto,think,no_think
- fix analysis think no_think and yield coroutine to speak
- add Kwai-Keye vlm case on modal 
```shell
https://huggingface.co/Kwai-Keye/Keye-VL-8B-Preview
Following Qwen3, keye also offer a soft switch mechanism
- nothing(default): auto analysis model 
- no-thinking: (<analysis>***</analysis>xxxxx)
- thinking: (<analysis>***</analysis><think>***</think><answer>xxxxx</answer>)
- /think: thinking model (<think>***</think><answer>xxxxx</answer>)
- /no_think: no thinking model (xxxxx)
modal run src/download_models.py --repo-ids …
```
=> Feat: add Kwai-Keye vlm

README.md, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/llm/transformers/vlm/glm4v.py, pyproject.toml, src/core/llm/__init__.py, src/core/llm/transformers/manual_vision_glm4v.py
> [!TIP]
> - GLM-4.1V-Thinking 9B 模型 chat template 仅支持 thinking 模式， 如果需要禁用thinking， 可以修改模版或者2次推理(第一次推理截断后继续推理)
-  if want disable thinking, just run answer, download this pr: https://huggingface.co/THUDM/GLM-4.1V-9B-Thinking/discussions/9
> - GLM-4.1V-Base 9B 模型 是个基础模型，不支持chat， 以及think模式，按照GLM-4.1V-Thinking论文中的训练方式，可以结合场景数据进行后训练(sft, RL)复现，RL可以使用verl框架
> - GLM-4.1V-Thinking 不支持 Agentic (function call)模式，可以在该模型基础上用对应agent数据进行微调
PS: 
- 对比快手的Keye(https://github.com/ai-bot-pro/achatbot/pull/168)直接提供推理模型，支持Auto-Thinking, Thinking, Non-Thinking ，对于只需推理的场景相对比较灵活，但是如果基于已经训练好的推理模型，如果针对场景进行RL再次微调，可能效果不如直接使用基础模型进行后训练来的效果好些； 
- GLM-4.1V-Base 则已经集成了视觉功能，后训练可以结合场景数据进行SFT,RL, 可以按照 Keye 后训练的Auto-Thinking, Thinking, Non-Thinking, Agentic 模式的数据格式进行训练 🤔
---
AI Podcast:
- GLM-4.1V-Thinking: …
=> Feat: add GLM-4.1V-Thinking vlm

deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/llm/fastdeploy/offline_inference.py, pyproject.toml, src/core/llm/fastdeploy/base.py, src/core/llm/fastdeploy/generator.py, src/core/llm/fastdeploy/vision_ernie4v.py
feat: 
- add non-thinking mode for llm_fastdeploy_vision_ernie4v room bot
use `replace("<think>", "<think>\n</think>\n")` can close thinking mode (like qwen3)
```shell
EXTRA_INDEX_URL=https://pypi.org/simple/ \
SERVE_TYPE=room_bot \
CONFIG_FILE=/root/.achatbot/config/bots/daily_describe_fastdeploy_ernie4v_vision_bot.json \
ACHATBOT_VERSION=0.0.21.post0 \
IMAGE_NAME=fastdeploy_ernie4v IMAGE_CONCURRENT_CN=1 IMAGE_GPU=L40s \
GPU_ARCHS=86_89 \
modal serve src/fastapi_webrtc_vision_bot_serve.py
```
daily_describe_fastdeploy_ernie4v_vision_bot.json (non-thinking mode `lm_gen_thinking:false` to init param)
```json
{
"chat_bot_name": "DailyDescribeVisionBot",
"room_name": "chat-room",
"room_url": "",
"token": "",
"room_manager": {
"tag": "daily_room",
"args": {
"privacy": "public"
}
}, …
```
=> Feat: add non-thinking mode for llm_fastdeploy_vision_ernie4v bot

deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/llm/transformers/vlm/skywork_r1v.py, pyproject.toml, src/core/llm/__init__.py, src/core/llm/transformers/base.py, src/core/llm/transformers/manual_vision_skyworkr1v.py, src/processors/vision/vision_processor.py, src/types/llm/transformers.py
InternVL3:
Post-Training:
0. Reward Function Design:
1. Cold Start Finetuning:
2. Reinforcement Finetuning:
3. Connector-Only Tuning:
Slow-Thinking/No-Thinking/NoWait(Fast-Thinking):
---
AI Podcast:
- Skywork-VL Reward: https://podcast-997.pages.dev/podcast/286397147aec48969a0e3afd01f6fb1c
- Skywork-R1V3: https://podcast-997.pages.dev/podcast/9979b3505faf4b008c58953a801f1a08
- NoWait: https://podcast-997.pages.dev/podcast/e556107a99c141bcbfe8dd0e7f7dde12
---
> [!TIP]
> - 使用开源的VIT 和 预训练模型（InternVL-38B （[InternViT-6B-448px-V2_5](https://huggingface.co/OpenGVLab/InternViT-6B-448px-V2_5) + [Qwen2.5-32B](https://huggingface.co/Qwen/Qwen2.5-32B) ）） 作为骨干网络（遵循“ViT-MLP-LLM”范式）， 主要关注后训练的数据建设，以及RL的奖励机制的设计
> - RL训练使用verl框架训练，具体实操见：https://github.com/ai-bot-pro/achatbot/pull/155
---
feat:
- add …
=> Feat: add SkyworkR1V

README.md, deploy/modal/src/fastapi_webrtc_gemma3n_vision_speech_bot_serve.py, deploy/modal/src/fastapi_webrtc_vision_bot_serve.py, deploy/modal/src/llm/transformers/gemma3n.py, pyproject.toml, src/cmd/bots/__init__.py, src/cmd/bots/base.py, src/cmd/bots/omni/daily_gemma3n_vision_speech_bot.py, src/common/chat_history.py, src/core/llm/__init__.py, src/core/llm/base.py, src/core/llm/transformers/base.py, src/core/llm/transformers/manual_vision_gemma.py, src/core/llm/transformers/manual_vision_skyworkr1v.py, src/core/llm/transformers/manual_vision_speech_gemma3n.py, src/modules/speech/asr/__init__.py, src/modules/speech/asr/gemma3n_asr.py, src/processors/omni/gemma_vision_speech.py, src/types/llm/sampling.py, test/modules/speech/asr/test_gemma3n_asr.py
---
AI Podcast:
- MatFormer: https://podcast-997.pages.dev/podcast/1c26426a261045f993a4974af01ccbd5
> [!TIP]
> - transformers 库中对kv cache的策略可以看 https://huggingface.co/docs/transformers/kv_cache 了解
> - gemma 因为结构的特殊，没有使用flash attention 推理优化，以及在推理生成时需要加上kv cache策略，默认dynamic，这样在进行chat 上下文推理时，不会报错， 具体见这个issue： https://github.com/huggingface/transformers/issues/39498 
> - 最终的问题可能在于torch的多线程编译 cudagraphs  时存在问题，context 会触发`assert torch._C._is_key_in_tls(attr_name)` 见：https://github.com/huggingface/transformers/issues/39498
> - 语音识别，识别中文，会输出繁体中文，如果使用简体中文输出，有时会出错, 需要微调任务。
> - 支持语音+图片 描述，但是单独进行语音聊天时，还是会进行图片描述（即使使用提示词进行说明）， 需要微调任务。
> - 主要面向终端端侧部署的网络结构。参数可以变动调整， 可以选择参数，并组装大小介于 2B 和 4B 之间的中间大小的模型
---
feat:
- add gemma3n transformers text/audio/image case test
```shell
Gemma 3n:
Multimodal: 2b, 4b …
```
=> feat: add Gemma3n(text/audio/image)

deploy/modal/src/turn/smart_turn_v2_predict.py, pyproject.toml, src/cmd/bots/__init__.py, src/cmd/bots/turn/agora_turn_bot.py, src/cmd/bots/turn/daily_turn_bot.py, src/cmd/bots/turn/livekit_turn_bot.py, src/common/interface.py, src/common/types.py, src/modules/speech/turn_analyzer/__init__.py, src/modules/speech/turn_analyzer/smart_turn.py, src/processors/audio_input_processor.py, src/types/ai_conf.py, src/types/frames/sys_frames.py, src/types/metrics/metrics.py, src/types/speech/turn_analyzer/__init__.py, src/types/speech/turn_analyzer/smart_turn.py, test/modules/speech/turn_analyzer/test_smart_turn.py
> [!TIP]
> - smart-turn-v2 使用wav2vec2-base-960h（只有base/large版本）作为基础模型来进行语音语义特征抽取分析，使用线性分类器进行判别说话语音是否结束（整体模型 95M参数）；
> - 还可以使用其他模型比如： [2020.5 comformer](https://arxiv.org/abs/2005.08100) (CNN+Attention) (几乎和[2020.6 wav2vec2](https://arxiv.org/abs/2006.11477) 同一时期发表)，[2022.6 squeezeformer](https://arxiv.org/abs/2206.00888) 以及[2022.12 whisper](https://arxiv.org/abs/2212.04356), [2023.5 **fastconformer**](https://arxiv.org/abs/2305.05084)  [2023.10 zipformer](https://arxiv.org/abs/2310.11230) (NLA) 作为基础模型进行语音语义抽取，尝试使用不同参数大小的模型进行评估;
> - 分类问题适合人工评估，可以收集用户行为数据，以便后续模型升级迭代；
---
feat:
- add speech smart end turn analyzer and test case
```shell
TURN_ANALYZER_TAG=v2_smart_turn_analyzer python -m unittest test.modules.speech.turn_analyzer.test_smart_turn.TestTurnAnalyzer.test_end …
```
=> Feat: add smart end turn speech detect

deploy/modal/src/fastapi_webrtc_translate_bot_serve.py, deploy/modal/src/fastapi_ws_translate_bot_serve.py, deploy/modal/src/llm/trtllm/examples/compile_model.py, deploy/modal/src/llm/trtllm/examples/generator.py, deploy/modal/src/llm/trtllm/translation/compile_model.py, deploy/modal/src/llm/trtllm/translation/seed_x.py, deploy/modal/src/llm/trtllm/trtllm_latency.py, deploy/modal/src/llm/trtllm/tts_spark/triton_backend_tensorrtllm.py, deploy/modal/src/llm/trtllm/whisper/compile_model.py, deploy/modal/src/llm/trtllm/whisper/tritonserver.py, pyproject.toml, src/cmd/bots/base.py, src/cmd/webrtc/signaling_bot_server.py, src/cmd/websocket/server/fastapi_ws_bot_serve.py, src/common/interface.py, src/core/llm/ctranslate2/generator.py, src/core/llm/fastdeploy/generator.py, src/core/llm/llamacpp/__init__.py, src/core/llm/sglang/generator.py, src/core/llm/tensorrt_llm/generator.py, src/core/llm/transformers/generator.py, src/core/llm/vllm/generator.py, src/types/llm/transformers.py
feat: 
- add tensorrt-llm latency test on H100 for Meta-Llama-3-8B-Instruct (Mistral-7B(seed-x) the same as llama)
```shell
modal run src/llm/trtllm/trtllm_latency.py --mode=slow
🏎️  mode=slow inference latency (p50, p90): (660.99ms, 2547.70ms)
modal run src/llm/trtllm/trtllm_latency.py 
🏎️  mode=fast inference latency (p50, p90): (194.02ms, 748.77ms)
```
---
- add tensorrt-llm translate llm generator 
```shell
modal run src/download_models.py --repo-ids "FunAudioLLM/SenseVoiceSmall"
modal run src/download_models.py::download_modelscope_models --repo-ids "iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch"
modal run src/download_models.py --repo-ids "ByteDance-Seed/Seed-X-PPO-7B"
```
```shell
IMAGE_GPU=L4 modal run src/llm/trtllm/translation/seed_x.py::run_achatbot_generator
modal …
```
=> feat: add tensorrt-llm translate llm generator and deploy websocket/webrtc http asr+translate+tts bot server

README.md, demo/nest_async.py, deploy/modal/src/fastapi_ws_translate_bot_serve.py, deploy/modal/src/llm/ctranslate2/seed_x.py, deploy/modal/src/llm/transformers/translation/hunyuan_mt.py, deploy/modal/src/llm/transformers/translation/seed_x.py, pyproject.toml, src/cmd/bots/base.py, src/cmd/bots/translation/agora_asr_translate_tts_bot.py, src/cmd/bots/translation/daily_asr_translate_tts_bot.py, src/cmd/bots/translation/fastapi_websocket_server_asr_translate_tts_bot.py, src/cmd/bots/translation/livekit_asr_translate_tts_bot.py, src/cmd/bots/translation/small_webrtc_asr_translate_tts_bot.py, src/core/llm/llamacpp/generator.py, src/core/llm/sglang/generator.py, src/core/llm/transformers/generator.py, src/processors/translation/llm_translate_processor.py, src/types/ai_conf.py, src/types/llm/sglang.py
<details>
<summary>💡</summary>
> [!TIP]
> - 搞社交的高质量数据多多挖掘，喂给模型，压缩好之后，喂给开源社区发展，谢谢
> - 搞社会吃穿住行的agentic 工具型高质量数据多多挖掘，喂给模型，压缩好之后，喂给开源社区发展，谢谢
</details>
feat:
- add Hunyuan-MT and Seed-X transformers generator translation test
- Seed-X
```shell
modal run src/download_models.py --repo-ids "ByteDance-Seed/Seed-X-PPO-7B"
modal run src/llm/transformers/translation/seed_x.py --task tokenize
IMAGE_GPU=T4 modal run src/llm/transformers/translation/seed_x.py --task dump_model
IMAGE_GPU=T4 modal run src/llm/transformers/translation/seed_x.py --task generate
IMAGE_GPU=L4 modal run src/llm/transformers/translation/seed_x.py --task generate
IMAGE_GPU=T4 modal run src/llm/transformers/translation/seed_x.py --task generate_stream
IMAGE_GPU=L4 modal run src/llm/transformers/translation/seed_x.py --task …
```
=> feat: add Hunyuan-MT and Seed-X transformers generator translation test; run websocket/webrtc asr+translate+tts bot serve for Hunyuan-MT

deploy/modal/src/llm/vllm/qwen3_omni_fork.py, src/cmd/bots/SE/livekit_noise_filter_bot.py, src/cmd/bots/__init__.py, src/common/utils/audio_resample.py, src/modules/speech/enhancer/__init__.py, src/modules/speech/enhancer/__main__.py, src/modules/speech/enhancer/ans_gtcrn_onnx.py, src/thirdparty/streaming_gtcrn/convert.py, src/thirdparty/streaming_gtcrn/convert_onnx.py, src/thirdparty/streaming_gtcrn/convolution.py, src/thirdparty/streaming_gtcrn/gtcrn.py, src/thirdparty/streaming_gtcrn/gtcrn_stream.py
---
feat:
- add streaming gtcrn model (stream, convert to stream, onnx)
```shell
wget https://github.com/Xiaobin-Rong/gtcrn/raw/refs/heads/main/stream/onnx_models/model_trained_on_vctk.tar -O ./models/model_trained_on_vctk.tar
wget https://github.com/Xiaobin-Rong/gtcrn/raw/refs/heads/main/stream/onnx_models/model_trained_on_dns3.tar -O ./models/model_trained_on_dns3.tar
wget https://github.com/Xiaobin-Rong/gtcrn/raw/refs/heads/main/test_wavs/mix.wav -O ./records/mix.wav
python -m src.thirdparty.streaming_gtcrn.gtcrn_stream
NOTE: 根据场景(dataset)PT哦~ (结合场景，更精细一些，对应硬件芯片和DNN模型结构的相互适配)
```
- add enhancer_ans_gtcrn_onnx engine
```shell
SPEECH_ENHANCER_TAG=enhancer_ans_gtcrn_onnx python -m src.modules.speech.enhancer
```
- add LivekitAudioNoiseFilterBot
- add filter audio noise bot with GTCRN SE …
=> feat: add GTCRN SE to filter audio noise
